export const photos =
[
            '../../assets/images/Season 1 Art/Opportunity- Edward R. Sill 1.png',
            '../../assets/images/Season 1 Art/Opportunity- Edward R. Sill 2.png',
            '../../assets/images/Season 1 Art/Opportunity- Edward R. Sill 3.png',
            '../../assets/images/Season 1 Art/Invictus- William Ernest Henley 1.png',
            '../../assets/images/Season 1 Art/Invictus- William Ernest Henley 2.png',
            '../../assets/images/Season 1 Art/Invictus- William Ernest Henley 3.png',
            '../../assets/images/Season 1 Art/Invictus- William Ernest Henley 4.png',
            '../../assets/images/Season 1 Art/Ode 1.11 - Horace 1.png',
            '../../assets/images/Season 1 Art/Ode 1.11 - Horace 2.png',
            '../../assets/images/Season 1 Art/Ode 1.11 - Horace 3.png',
            '../../assets/images/Season 1 Art/Ode 1.11 - Horace 4.png',    
            '../../assets/images/Season 1 Art/“The Builders_ by Henry Wadsworth Longfellow 1.png',
            '../../assets/images/Season 1 Art/“The Builders_ by Henry Wadsworth Longfellow 2.png',
            '../../assets/images/Season 1 Art/“The Builders_ by Henry Wadsworth Longfellow 3.png',
            '../../assets/images/Season 1 Art/“The Builders_ by Henry Wadsworth Longfellow 4.png',
            '../../assets/images/Season 1 Art/“The Builders_ by Henry Wadsworth Longfellow 5.png',
            '../../assets/images/Season 1 Art/“The Builders_ by Henry Wadsworth Longfellow 6.png',
            '../../assets/images/Season 1 Art/“The Builders_ by Henry Wadsworth Longfellow 7.png',
            '../../assets/images/Season 1 Art/“The Builders_ by Henry Wadsworth Longfellow 8.png',
            '../../assets/images/Season 1 Art/“The Builders_ by Henry Wadsworth Longfellow 9.png',
            '../../assets/images/Season 1 Art/“Ozymandias_ by Percy Bysshe Shelley 1.png',
            '../../assets/images/Season 1 Art/“Ozymandias_ by Percy Bysshe Shelley 2.png',
            '../../assets/images/Season 1 Art/“Ozymandias_ by Percy Bysshe Shelley 3.png',
            '../../assets/images/Season 1 Art/“Ozymandias_ by Percy Bysshe Shelley 4.png',
            '../../assets/images/Season 1 Art/“Crumbling is not an instants Act_ by Emily Dickinson 1.png',
            '../../assets/images/Season 1 Art/“Crumbling is not an instants Act_ by Emily Dickinson 2.png',
            '../../assets/images/Season 1 Art/“Crumbling is not an instants Act_ by Emily Dickinson 3.png',
            '../../assets/images/Season 1 Art/If_ by Rudyard Kipling 1.png',
            '../../assets/images/Season 1 Art/If_ by Rudyard Kipling 2.png',
            '../../assets/images/Season 1 Art/If_ by Rudyard Kipling 3.png',
            '../../assets/images/Season 1 Art/If_ by Rudyard Kipling 4.png',
            '../../assets/images/Season 1 Art/If_ by Rudyard Kipling 5.png',
            '../../assets/images/Season 1 Art/If_ by Rudyard Kipling 6.png',
            '../../assets/images/Season 1 Art/If_ by Rudyard Kipling 7.png',
            '../../assets/images/Season 1 Art/If_ by Rudyard Kipling 8.png',
            '../../assets/images/Season 1 Art/_The Debt_ by Paul Laurence Dunbar 1.png',
            '../../assets/images/Season 1 Art/_The Debt_ by Paul Laurence Dunbar 2.png',
            '../../assets/images/Season 1 Art/_The Debt_ by Paul Laurence Dunbar 3.png',
            '../../assets/images/Season 1 Art/“Old Ironsides_ by Oliver Wendell Holmes Sr. 1.png',
            '../../assets/images/Season 1 Art/“Old Ironsides_ by Oliver Wendell Holmes Sr. 2.png',
            '../../assets/images/Season 1 Art/“Old Ironsides_ by Oliver Wendell Holmes Sr. 3.png',
            '../../assets/images/Season 1 Art/“Old Ironsides_ by Oliver Wendell Holmes Sr. 4.png',
            '../../assets/images/Season 1 Art/“Old Ironsides_ by Oliver Wendell Holmes Sr. 5.png',
            '../../assets/images/Season 1 Art/“Old Ironsides_ by Oliver Wendell Holmes Sr. 6.png',
            '../../assets/images/Season 1 Art/“How Did You Die__ by Edmund Vance Cooke 1.png',
            '../../assets/images/Season 1 Art/“How Did You Die__ by Edmund Vance Cooke 2.png',
            '../../assets/images/Season 1 Art/“How Did You Die__ by Edmund Vance Cooke 3.png',
            '../../assets/images/Season 1 Art/“How Did You Die__ by Edmund Vance Cooke 4.png',
            '../../assets/images/Season 1 Art/“How Did You Die__ by Edmund Vance Cooke 5.png',
            '../../assets/images/Season 1 Art/“How Did You Die__ by Edmund Vance Cooke 6.png',
            '../../assets/images/Season 1 Art/“Ulysses_ by Alfred Lord Tennyson 1.png',
            '../../assets/images/Season 1 Art/“Ulysses_ by Alfred Lord Tennyson 2.png',
            '../../assets/images/Season 1 Art/“Ulysses_ by Alfred Lord Tennyson 3.png',
            '../../assets/images/Season 1 Art/“Ulysses_ by Alfred Lord Tennyson 4.png',
            '../../assets/images/Season 1 Art/“Ulysses_ by Alfred Lord Tennyson 5.png',
            '../../assets/images/Season 1 Art/“Ulysses_ by Alfred Lord Tennyson 6.png',
            '../../assets/images/Season 1 Art/“Ulysses_ by Alfred Lord Tennyson 7.png',
            '../../assets/images/Season 1 Art/“Ulysses_ by Alfred Lord Tennyson 8.png',
            '../../assets/images/Season 1 Art/“Ulysses_ by Alfred Lord Tennyson 8.png',
            '../../assets/images/Season 1 Art/“Ulysses_ by Alfred Lord Tennyson 10.png',
            '../../assets/images/Season 1 Art/“Ulysses_ by Alfred Lord Tennyson 11.png',
            '../../assets/images/Season 1 Art/“And death shall have no dominion” by Dylan Thomas 1.png',
            '../../assets/images/Season 1 Art/“And death shall have no dominion” by Dylan Thomas 2.png',
            '../../assets/images/Season 1 Art/“And death shall have no dominion” by Dylan Thomas 3.png',
           //add Christmas Bells by Longfellow?
    ];